CREATE SCHEMA FLOW_RELIABILITY AUTHORIZATION SYSDBA;

CREATE TABLE FLOW_RELIABILITY.WORKFLOW_BUSINESS_INSTANCE
(
    ID BIGINT IDENTITY(1, 1) NOT NULL,
    BUSINESS_ID VARCHAR(200) NOT NULL,
    BUSINESS_TYPE VARCHAR(100) NOT NULL,
    PROCESS_INSTANCE_ID VARCHAR(100),
    PROCESS_DEFINITION_KEY VARCHAR(200) NOT NULL,
    PROCESS_DEFINITION_VERSION INT,
    FLOW_STATE VARCHAR(40) NOT NULL,
    CALLBACK_STATE VARCHAR(40) NOT NULL,
    CALLBACK_CONFIG_SNAPSHOT CLOB,
    ROW_VERSION BIGINT DEFAULT 0 NOT NULL,
    DATA_VERSION BIGINT DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    COMPLETED_AT TIMESTAMP(6),
    CONSTRAINT PK_WORKFLOW_BUSINESS_INSTANCE PRIMARY KEY (ID),
    CONSTRAINT UK_WORKFLOW_BUSINESS_ID UNIQUE (BUSINESS_ID),
    CONSTRAINT UK_WORKFLOW_PROCESS_INSTANCE UNIQUE (PROCESS_INSTANCE_ID)
);

CREATE TABLE FLOW_RELIABILITY.WORKFLOW_CALLBACK_EVENT
(
    EVENT_ID VARCHAR(64) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR(500) NOT NULL,
    BUSINESS_ID VARCHAR(200) NOT NULL,
    PROCESS_INSTANCE_ID VARCHAR(100) NOT NULL,
    CALLBACK_ACTIVITY_ID VARCHAR(200) NOT NULL,
    CALLBACK_TYPE VARCHAR(80) NOT NULL,
    PAYLOAD CLOB NOT NULL,
    STATUS VARCHAR(40) NOT NULL,
    ATTEMPT_COUNT INT DEFAULT 0 NOT NULL,
    NEXT_ATTEMPT_AT TIMESTAMP(6),
    LEASE_OWNER VARCHAR(200),
    LEASE_UNTIL TIMESTAMP(6),
    LAST_HTTP_STATUS INT,
    LAST_ERROR CLOB,
    CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONFIRMED_AT TIMESTAMP(6),
    COMPLETED_AT TIMESTAMP(6),
    ROW_VERSION BIGINT DEFAULT 0 NOT NULL,
    CONSTRAINT PK_WORKFLOW_CALLBACK_EVENT PRIMARY KEY (EVENT_ID),
    CONSTRAINT UK_WORKFLOW_CALLBACK_IDEMPOTENCY UNIQUE (IDEMPOTENCY_KEY)
);

CREATE INDEX FLOW_RELIABILITY.IX_CALLBACK_DUE
    ON FLOW_RELIABILITY.WORKFLOW_CALLBACK_EVENT (STATUS, NEXT_ATTEMPT_AT);
CREATE INDEX FLOW_RELIABILITY.IX_CALLBACK_PROCESS
    ON FLOW_RELIABILITY.WORKFLOW_CALLBACK_EVENT (PROCESS_INSTANCE_ID);
CREATE INDEX FLOW_RELIABILITY.IX_CALLBACK_BUSINESS
    ON FLOW_RELIABILITY.WORKFLOW_CALLBACK_EVENT (BUSINESS_ID);
CREATE INDEX FLOW_RELIABILITY.IX_CALLBACK_LEASE
    ON FLOW_RELIABILITY.WORKFLOW_CALLBACK_EVENT (LEASE_UNTIL);
