CREATE TABLE FLOW_RELIABILITY.WORKFLOW_CALLBACK_LEASE
(
    EVENT_ID VARCHAR(64) NOT NULL,
    LEASE_OWNER VARCHAR(200) NOT NULL,
    LEASE_UNTIL TIMESTAMP(6) NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_WORKFLOW_CALLBACK_LEASE PRIMARY KEY (EVENT_ID)
);

CREATE INDEX FLOW_RELIABILITY.IX_CALLBACK_LEASE_EXPIRY
    ON FLOW_RELIABILITY.WORKFLOW_CALLBACK_LEASE (LEASE_UNTIL);
