CREATE TABLE FLOW_RELIABILITY.WORKFLOW_DEFINITION_CONFIG
(
    ID BIGINT IDENTITY(1, 1) NOT NULL,
    PROCESS_DEFINITION_KEY VARCHAR(200) NOT NULL,
    PROCESS_DEFINITION_VERSION INT NOT NULL,
    PROCESS_DEFINITION_ID VARCHAR(200) NOT NULL,
    CONTENT_HASH VARCHAR(128) NOT NULL,
    CONFIG_JSON CLOB NOT NULL,
    DATA_VERSION BIGINT DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_WORKFLOW_DEFINITION_CONFIG PRIMARY KEY (ID),
    CONSTRAINT UK_WORKFLOW_DEFINITION_VERSION
        UNIQUE (PROCESS_DEFINITION_KEY, PROCESS_DEFINITION_VERSION)
);

CREATE TABLE FLOW_RELIABILITY.WORKFLOW_TASK_ACTION
(
    ACTION_ID VARCHAR(64) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR(500) NOT NULL,
    BUSINESS_ID VARCHAR(200) NOT NULL,
    PROCESS_INSTANCE_ID VARCHAR(100) NOT NULL,
    TASK_ID VARCHAR(100),
    TASK_DEFINITION_KEY VARCHAR(200),
    ACTION_TYPE VARCHAR(80) NOT NULL,
    OPERATOR_ID VARCHAR(200) NOT NULL,
    REQUEST_JSON CLOB,
    RESULT_STATE VARCHAR(40) NOT NULL,
    FLOWABLE_RESULT VARCHAR(40),
    LAST_ERROR CLOB,
    DATA_VERSION BIGINT DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_WORKFLOW_TASK_ACTION PRIMARY KEY (ACTION_ID),
    CONSTRAINT UK_WORKFLOW_TASK_ACTION_IDEMPOTENCY UNIQUE (IDEMPOTENCY_KEY)
);

CREATE INDEX FLOW_RELIABILITY.IX_TASK_ACTION_PROCESS
    ON FLOW_RELIABILITY.WORKFLOW_TASK_ACTION (PROCESS_INSTANCE_ID, CREATED_AT);

CREATE TABLE FLOW_RELIABILITY.WORKFLOW_SCHEMA_VERSION
(
    VERSION_NO INT NOT NULL,
    DESCRIPTION VARCHAR(500) NOT NULL,
    APPLIED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_WORKFLOW_SCHEMA_VERSION PRIMARY KEY (VERSION_NO)
);

INSERT INTO FLOW_RELIABILITY.WORKFLOW_SCHEMA_VERSION
    (VERSION_NO, DESCRIPTION)
VALUES
    (3, 'definition config, task action and migration ledger');
