ALTER TABLE FLOW_RELIABILITY.WORKFLOW_BUSINESS_INSTANCE
    ADD RECOMMENDED_ASSIGNEES_SNAPSHOT CLOB;

INSERT INTO FLOW_RELIABILITY.WORKFLOW_SCHEMA_VERSION
    (VERSION_NO, DESCRIPTION)
VALUES
    (4, 'authoritative recommended assignee snapshot');
