DELETE FROM FLOW_RELIABILITY.WORKFLOW_SCHEMA_VERSION
WHERE VERSION_NO = 5;

ALTER TABLE FLOW_RELIABILITY.WORKFLOW_BUSINESS_INSTANCE
    DROP COLUMN NODE_DESCRIPTIONS_SNAPSHOT;

ALTER TABLE FLOW_RELIABILITY.WORKFLOW_BUSINESS_INSTANCE
    DROP COLUMN CREATED_BY;

ALTER TABLE FLOW_RELIABILITY.WORKFLOW_BUSINESS_INSTANCE
    DROP COLUMN BUSINESS_TITLE;
