ALTER TABLE FLOW_RELIABILITY.WORKFLOW_BUSINESS_INSTANCE
    ADD BUSINESS_TITLE VARCHAR(500);

ALTER TABLE FLOW_RELIABILITY.WORKFLOW_BUSINESS_INSTANCE
    ADD CREATED_BY VARCHAR(100);

ALTER TABLE FLOW_RELIABILITY.WORKFLOW_BUSINESS_INSTANCE
    ADD NODE_DESCRIPTIONS_SNAPSHOT CLOB;

INSERT INTO FLOW_RELIABILITY.WORKFLOW_SCHEMA_VERSION
    (VERSION_NO, DESCRIPTION)
VALUES
    (5, 'pending task business context and instance node descriptions');
